# Generated by Django 5.1.5 on 2025-02-25 05:14

import django.db.models.deletion
import django_countries.fields
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('default_address_line_1', models.CharField(blank=True, max_length=150, null=True)),
                ('default_address_line_2', models.CharField(blank=True, max_length=150, null=True)),
                ('default_address_line_3', models.CharField(blank=True, max_length=150, null=True)),
                ('default_town', models.CharField(blank=True, max_length=50, null=True)),
                ('default_postcode', models.CharField(blank=True, max_length=15, null=True)),
                ('default_country', django_countries.fields.CountryField(countries=profiles.models.AllowedCountries, max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
