# Generated by Django 5.1.5 on 2026-08-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_address_line_3',
        ),
    ]
