# Generated by Django 5.1.5 on 2026-08-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_line_3',
        ),
    ]
