# Generated by Django 5.1.5 on 2026-08-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_original_bag_order_stripe_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
