# Generated by Django 5.1.5 on 2026-08-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='business_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
