# Generated by Django 5.1.5 on 2026-08-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='business_name',
            field=models.CharField(max_length=150),
        ),
    ]
