# Generated by Django 5.1.5 on 2025-04-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_us_form',
        ),
    ]
