# Generated by Django 3.2.25 on 2024-11-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='describtion',
            new_name='description',
        ),
    ]
