# Generated by Django 5.1.5 on 2025-02-25 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_pic_loc',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_vat',
        ),
    ]
