# Generated by Django 5.1.5 on 2025-04-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_subcategory_id_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
