# Generated by Django 5.1.5 on 2026-08-21 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_bulk_price_product_bulk_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bulk_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
